### ISSUE TITLE
ComBatv3.34 algorithm

### ISSUE THREAD

**Issue by OrhunKok** [UCLouvain-CBIO/SCP.replication#2]
For the section that runs the ComBatv3.34 algorithm:

 assay(sce) <- ComBatv3.34(dat = assay(sce), 
                           batch = batch, 
                           mod = model)

I am getting this error: 

Error in postmean(gamma.hat[i, ], gamma.bar[i], 1, 1, t2[i]) : 
  could not find function "postmean"

**Comment by lgatto** [comment]
You can source that extra function [here](https://github.com/UCLouvain-CBIO/2021-SCoPE2-replication/blob/main/utils.R). We are working on a dedicated replication package that (will contain that function out of the box). Should be ready tomorrow or the day after.
