### ISSUE TITLE
Choice of quantitative information in readSCPfromDIANN function

### ISSUE THREAD

**Issue by KristinaGomoryova** [UCLouvain-CBIO/SCP.replication#23]
Hello,

would you consider adding a new argument to the `readSCPfromDIANN` function, where user could choose which column containing quantitative information (e.g. PG.Quantity, PG.Normalised or PG.MaxLFQ) will be used? Currently it seems to be using MS1.Area column by default - and when analyzing DIA data, I would prefer actually using different one, e.g. PG.Quantity.

Thanks a lot for considering!

**Comment by cvanderaa** [comment]
Hello @KristinaGomoryova!

You are right, up to now only the `Ms1.Area` column is considered when fetching the quantitative info. I think it is about time to move `readSCPfromDIANN` from this repo to the `scp` package. In the `scp` package, I added an argument to the function so you can select another column. 

I created a new issue in the `scp` package: https://github.com/UCLouvain-CBIO/scp/issues/42. I suggest we move the discussion to that issue and I will close this one.
