### ISSUE TITLE
Update man pages

### ISSUE THREAD

**Issue by lgatto** [UCLouvain-CBIO/SCP.replication#3]
Need to fill out the roxygen header in the R files to generate valid man pages.

**Comment by cvanderaa** [comment]
Done by 84e8a38c5ae471e6fe864b8d8b00caad7debb260. 

Maybe we could think about integrating `countUniqueFeatures` into a dedicated package such as `scp` or `QFeatures`. What do you think?

**Comment by lgatto** [comment]
Of course - I think `QFeatures` would be a good home.
