### ISSUE TITLE
`zhu2019EL` dataset becomes inconsistent

### ISSUE THREAD

**Issue by cvanderaa** [UCLouvain-CBIO/SCP.replication#8]
The `zhu2019EL` becomes inconsistent after [this filter command](https://github.com/UCLouvain-CBIO/SCP.replication/blob/61788f63b374c210338991dd74e6c98d7ff194a2/vignettes/zhu2019EL.Rmd#L266-L268). An error pops out when running this code after the filtering, but not before:
```r
sel <- rowSums(!is.na(assay(scp[["proteins_iBAQ"]]))) >= 5
sel <- names(sel)[sel]
scp[sel, , ]
```

Once this issue is solved, [this line](https://github.com/UCLouvain-CBIO/SCP.replication/blob/61788f63b374c210338991dd74e6c98d7ff194a2/vignettes/zhu2019EL.Rmd#L739) should be replaced by:

```r
scp <- scp[sel, , ]
```

**Comment by lgatto** [comment]
Is this still relevant ?

**Comment by cvanderaa** [comment]
I think this is still relevant. I'll work on this as soon as possible!

**Comment by cvanderaa** [comment]
Ok I finally found the issue! When using `filterFeatures` the `AssayLinks` can become inconsistent and some peptides point towards PSMs that were removed. Those lost links are not detected. Solving this issue will first require a fix in `QFeatures`. 

Here is a reproducible example that illustrates the issue: 

```r
library(scpdata)
scp <- liang2020_hela()
scp <- filterFeatures(scp, ~ Reverse != "+")
## Get all PSM names from the data set
psms <- unlist(rownames(scp)[1:15])
## Get the PSMS from which the peptides are linked in the AssayLink in
## assay 15 (for instance)
linkedpsms <- elementMetadata(assayLink(scp, "peptides")@hits[[15]])$names_from
## Are all linked PSMs still present in the data? 
all(linkedpsms %in% psms)
## No, there is inconsistent linking !!

```

**Comment by cvanderaa** [comment]
This is now solved by recent changes in QFeatures (https://github.com/rformassspectrometry/QFeatures/pull/139)
